describe("raccoon", function()
  it("setup accepts empty options", function()
    local raccoon = require("raccoon")
    -- Should not error
    raccoon.setup({})
    assert.is_table(raccoon.config)
  end)

  it("setup merges user options", function()
    local raccoon = require("raccoon")
    raccoon.setup({ custom_option = "test" })
    assert.equals("test", raccoon.config.custom_option)
  end)

  it("defines inline diff highlight groups", function()
    local raccoon = require("raccoon")
    raccoon.setup({})

    local add = vim.api.nvim_get_hl(0, { name = "RaccoonAddInline", link = false })
    local del = vim.api.nvim_get_hl(0, { name = "RaccoonDeleteInline", link = false })
    assert.is_not_nil(add.bg)
    assert.is_not_nil(del.bg)
  end)

  it("uses one color intensity per diff side", function()
    local raccoon = require("raccoon")
    raccoon.setup({})

    local add = vim.api.nvim_get_hl(0, { name = "RaccoonAdd", link = false })
    local add_inline = vim.api.nvim_get_hl(0, { name = "RaccoonAddInline", link = false })
    local add_sign = vim.api.nvim_get_hl(0, { name = "RaccoonAddSign", link = false })
    local del = vim.api.nvim_get_hl(0, { name = "RaccoonDelete", link = false })
    local del_inline = vim.api.nvim_get_hl(0, { name = "RaccoonDeleteInline", link = false })
    local del_sign = vim.api.nvim_get_hl(0, { name = "RaccoonDeleteSign", link = false })

    assert.equals(add.bg, add_inline.bg)
    assert.equals(add.fg, add_inline.fg)
    assert.equals(add.fg, add_sign.fg)
    assert.equals(del.bg, del_inline.bg)
    assert.equals(del.fg, del_inline.fg)
    assert.equals(del.fg, del_sign.fg)
  end)
end)
